[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "chinatripinfo"
authors = [{name = "Shawn Guo", email = "shawnguo.cn@gmail.com"}]
dynamic = ["version", "description"]
